####################################
### Groups for the Automations view
####################################


sunset_automations:
  view: no
  name: Sunset Automations
  icon: mdi:home-automation
  entities:
    - automation.turn_off_floor_lamp_at_9pm_sunthur
    - automation.turn_on_bedroom_lights_after_sunset
    - automation.turn_on_lights_when_arriving_home_at_night
    - automation.turn_on_living_room_lights_after_sunset
    - automation.turn_off_all_lights_at_10pm
    - automation.turn_off_lights_when_nobody_at_home

media_automations:
  view: no
  name: Movie Time Automations
  icon: mdi:home-automation
  entities:
    - automation.media_player_paused
    - automation.media_player_paused_late_night
    - automation.media_player_playing
    - automation.media_player_stoped
    - automation.media_player_stoped_late_night
