- platform: fixer
  target: HUF

- platform: coinmarketcap
  currency: ethereum

- platform: coinmarketcap
  currency: bitcoin

- platform: coinmarketcap
  currency: litecoin

- platform: coinmarketcap
  currency: ripple
