#########################################
### Googgle Maps Travel Time integration
#########################################

- platform: google_travel_time
  name: Home to Chopra Center
  api_key: !secret google_map_api_key
  origin: zone.home
  destination: zone.chopra

- platform: google_travel_time
  name: Chopra Center to Home
  api_key: !secret google_map_api_key
  origin: zone.chopra
  destination: zone.home
